schema_version: 20180708
name: send_billing_to_s3
version: 0.0.1
runtime: python
build_image: fnproject/python:3.11-dev
run_image: fnproject/python:3.11
entrypoint: /python/bin/fdk /function/func.py handler
memory: 256
triggers:
- name: send_billing_to_s3
  type: http
  source: /send_billing_to_s3
